config/routes.rb
Rails.application.routes.draw do
  root to: 'videos#index'
  resources :videos do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/video.rb
class Video < ApplicationRecord
  has_one_attached :image
  has_one_attached :video

  with_options presence: true do
    validates :video
    validates :title
    validates :image
  end

  def self.search(search)
    if search != ""
      Video.where('title LIKE(?)', "%#{search}%")
    else
      Video.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:edit, :show, :destroy, :update]

  def index
    @videos = Video.all.order('created_at DESC')
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.create(video_params)
    if @video.valid?
      @video.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show

  end

  def search
    @videos = Video.search(params[:keyword])
  end

  def edit

  end

  def destroy
    if @video.destroy
      redirect_to root_path
    else
      redirect_to video_path(@video.id)
    end
  end

  def update
    if @video.update(video_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  private

  def video_params
    params.require(:video).permit(:video, :title, :image, :kifu)
  end

  def set_video
    @video = Video.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>神手順パラダイス</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="wrapper">
      <header>
        <div class="header_contents">
          <p class="app-title"><a href="/">神手順パラダイス</a></p>
            <div class="post-btn">
              <%= link_to "投稿", new_video_path, class: "post" %>
            </div>
        </div>
      </header>

        <%= yield %>

      <footer>
        <p>
          Copyright MiniTube.
        </p>
      </footer>
    </div>

  </body>

</html>

app/views/videos/edit.html.erb
<div class="whole">
  <div class="container">
    <%= form_with(model: @video, class: 'new-field', local: true) do |f| %>

      <div class="field">
        <%= f.label :video, '①動画', class: 'video-contents' %><span class="hissu">必須</span><br />
        <%= f.file_field :video, class: "inner" %>
      </div>

      <div class="field">
        <%= f.label :title, '②タイトル', class: '' %><span class="hissu">必須</span><br />
        <%= f.text_field :title, placeholder: '', class: "inner", size: "30x1" %>
      </div>

      <div class="field">
        <%= f.label :image, '③局面', class: '' %><span class="hissu">必須</span><br />
        <%= f.file_field :image, class: "inner" %>
      </div>

      <div class="field">
        <%= f.label :kifu, '④局面テキスト' %><span class="ninni">任意</span><br />
        <%= f.text_area :kifu, placeholder: 'kif形式で貼り付け', size: "25x5", class: "inner" %>
      </div>

      <div class="send">
        <%= f.submit "更新", class: 'send-btn' %>
      </div><br>

    <% end %>
  </div>
</div>

app/views/videos/index.html.erb
<div class="inner">
  <%= form_with(url: search_videos_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "タイトル検索", class: "search-input" %>
    <%= form.submit "🔎", class: "search-btn" %>
  <% end %>

  <div class="videos-row">
    <% @videos.each do |video| %>
      <div class="one-video">

        <div class="image">
          <%= image_tag video.image.variant(resize:'700x700') if video.image.attached? %>
        </div>

        <div class="title">
          <%= link_to video.title, video_path(video.id), class: 'title' %>
        </div>

      </div>
    <% end %>
  </div>
</div>

app/views/videos/new.html.erb
<div class="whole">
  <div class="container">
    <%= form_with(model: @video, class: 'new-field', local: true) do |f| %>

      <div class="field">
        <%= f.label :video, '①動画', class: 'video-contents' %><span class="hissu">必須</span><br />
        <%= f.file_field :video, class: "inner" %>
      </div>

      <div class="field">
        <%= f.label :title, '②タイトル', class: '' %><span class="hissu">必須</span><br />
        <%= f.text_field :title, placeholder: '', class: "inner", size: "30x1" %>
      </div>

      <div class="field">
        <%= f.label :image, '③局面', class: '' %><span class="hissu">必須</span><br />
        <%= f.file_field :image, class: "inner" %>
      </div>

      <div class="field">
        <%= f.label :kifu, '④局面テキスト' %><span class="ninni">任意</span><br />
        <%= f.text_area :kifu, placeholder: 'kif形式で貼り付け', size: "25x5", class: "inner" %>
      </div>

      <div class="send">
        <%= f.submit "アップロード", class: 'send-btn' %>
      </div><br>

    <% end %>
  </div>
</div>

app/views/videos/search.html.erb
<div class="inner">
  <%= form_with(url: search_videos_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "タイトル検索", class: "search-input" %>
    <%= form.submit "🔎", class: "search-btn" %>
  <% end %>

  <div class="videos-row">
    <% @videos.each do |video| %>
      <div class="one-video">

        <div class="image">
          <%= image_tag video.image.variant(resize:'700x700') if video.image.attached? %>
        </div>

        <div class="title">
          <%= link_to video.title, video_path(video.id), class: 'title' %>
        </div>

      </div>
    <% end %>
  </div>
</div>

app/views/videos/show.html.erb
<div class="video-row">

    <div class="one-video">

      <div class="video">
        <video src="<%= rails_blob_path(@video.video) %>" type="video/mp4" controls width="800" height="450" ></video>
      </div>

      <div class="show-title">
        <%= @video.title %>
      </div>

      <div class="kifu-text">
        <textarea id="fe_text" name="" rows="10" cols="40"><%= @video.kifu %></textarea>
      </div>

    </div>

    <div class="user_btn" >
      <div class="edit">
        <%= link_to "編集", edit_video_path(@video.id), method: :get, class: "edit-btn" %>
      </div>
      <div class="destroy">
        <%= link_to "削除", video_path(@video.id), method: :delete,  class: "destroy-btn" %>
      </div>
    </div >

</div>